name: CI/CD/CT Pipeline

on:
  push:
    branches:
      - main  # Se activa cuando hacemos push en la rama principal
  pull_request:
    branches:
      - main  # También se activa para pull requests en la rama principal

jobs:
  test:
    name: Ejecutar Pruebas Unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas unitarias
        run: |
          pytest test_pipeline.py --maxfail=5 --disable-warnings
          
  build:
    name: Construir el Proyecto
    runs-on: ubuntu-latest
    needs: test  # Este paso solo se ejecuta si el trabajo de pruebas (test) pasa

    steps:
      - name: Clonar el código del repositorio
        uses: actions/checkout@v2

      - name: Construir la aplicación
        run: echo "Construcción exitosa: Simulación de construcción de aplicación"

  deploy:
    name: Despliegue del Proyecto
    runs-on: ubuntu-latest
    needs: build  # Este paso solo se ejecuta si el trabajo de construcción (build) pasa

    steps:
      - name: Desplegar la aplicación
        run: echo "Despliegue exitoso: Simulación de despliegue final"
